// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brcrnuyvyplzrnynhmeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyY3JudXl2eXBsenJueW5obWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTI2ODAsImV4cCI6MjA3MTE4ODY4MH0.JcVWX_SlOjTleJoihFd48CYkdrlTjrpzmQqXwrVNuy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});